// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAccdm_7WqtlCfwcV9nruCsDrhQLWlCiBQ',
    appId: '1:908044330120:web:662524bd0825fa3de82b3d',
    messagingSenderId: '908044330120',
    projectId: 'task-a04e0',
    authDomain: 'task-a04e0.firebaseapp.com',
    storageBucket: 'task-a04e0.firebasestorage.app',
    measurementId: 'G-XM0V03MZE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsU43MQq8OvKXLTTLd6oISLXHJ8CCt-L8',
    appId: '1:908044330120:android:30415a6435baf2f5e82b3d',
    messagingSenderId: '908044330120',
    projectId: 'task-a04e0',
    storageBucket: 'task-a04e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5kddEQW7Vopn6e3cHdSoR2alBEyi1Feo',
    appId: '1:908044330120:ios:03e9c4d7f1b0e1f0e82b3d',
    messagingSenderId: '908044330120',
    projectId: 'task-a04e0',
    storageBucket: 'task-a04e0.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5kddEQW7Vopn6e3cHdSoR2alBEyi1Feo',
    appId: '1:908044330120:ios:03e9c4d7f1b0e1f0e82b3d',
    messagingSenderId: '908044330120',
    projectId: 'task-a04e0',
    storageBucket: 'task-a04e0.firebasestorage.app',
    iosBundleId: 'com.example.task',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAccdm_7WqtlCfwcV9nruCsDrhQLWlCiBQ',
    appId: '1:908044330120:web:e7c1ab300191180fe82b3d',
    messagingSenderId: '908044330120',
    projectId: 'task-a04e0',
    authDomain: 'task-a04e0.firebaseapp.com',
    storageBucket: 'task-a04e0.firebasestorage.app',
    measurementId: 'G-FZHEH3NFDC',
  );
}
